const { expect } = require('chai')

const { getNewReadMeContent } = require('./../change-readme.js')

describe('changeReadme', () => {

  it('it should with an insider release', () => {
    expect(
      getNewReadMeContent({
        releaseChannel: 'dev',
        npmVersion: '2.5.0-dev.4',
        githubActionContextSha: 'sha'
      })
    ).to.eq('<h2 align="center">Prisma VS Code Extension</h2>\r\n<div align="center">\r\n\r\n[![Version](https://vsmarketplacebadge.apphb.com/version/prisma.Prisma.svg)](https://marketplace.visualstudio.com/items?itemName=Prisma.prisma-insider)\r\n[![Installs](https://vsmarketplacebadge.apphb.com/installs/prisma.Prisma.svg)](https://marketplace.visualstudio.com/items?itemName=Prisma.prisma-insider)\r\n[![Ratings](https://vsmarketplacebadge.apphb.com/rating/prisma.Prisma.svg)](https://marketplace.visualstudio.com/items?itemName=Prisma.prisma-insider)\r\n\r\n![CI tests](https://img.shields.io/github/workflow/status/prisma/vscode/CI%20tests/master.svg?label=CI%20tests&logo=github)\r\n![Check for Update + Automated Publish](https://img.shields.io/github/workflow/status/prisma/vscode/Check%20for%20Update%20%2B%20Automated%20Publish/master.svg?label=Check%20for%20Update%20%2B%20Automated%20Publish&logo=github)\r\n\r\n\r\n</div>\r\n<hr>\r\n\r\n## Insider Build\r\n\r\nThis is the Insider Build of the [Prisma VSCode extension](https://marketplace.visualstudio.com/items?itemName=Prisma.prisma). Most users should not use this version, but instead install\r\nthe regular version of the extension.This version of the extension may contain unstable prerelease code and is directly built from the master branch. \r\n\r\n**Only use this extension if you are also using the dev version of the CLI.**\r\n\r\nPlease note that you should not have the regular and insider version of the extension installed at the same time.\r\n\r\n## Build information\r\n\r\nThis version is built from commit [sha](sha).\r\nThis is for Prisma CLI [2.5.0-dev.4](2.5.0-dev.4).\r\n\r\n## Contributing\r\n\r\nRead more about [how to contribute to the Prisma VSCode extension](./packages/vscode/CONTRIBUTING.md)\r\n\r\n## Telemetry\r\n\r\nThis extension collects telemetry data using [Azure Application Insights](https://www.npmjs.com/package/vscode-extension-telemetry) to help us better the usage of the extension.\r\nThe extension respects the `telemetry.enableTelemetry` setting in VSCode.\r\n\r\n## Security\r\n\r\nIf you have a security issue to report, please contact us at [security@prisma.io](mailto:security@prisma.io?subject=[GitHub]%20Prisma%202%20Security%20Report%20VSCode)\r\n')
  })

  it('it should work with a patch release', () => {
    expect(
        getNewReadMeContent({
            releaseChannel: 'patch-dev',
            npmVersion: '2.5.1-dev.1',
            githubActionContextSha: 'sha'
          })
    ).to.eq('<h2 align="center">Prisma VS Code Extension</h2>\r\n<div align="center">\r\n\r\n[![Version](https://vsmarketplacebadge.apphb.com/version/prisma.Prisma.svg)](https://marketplace.visualstudio.com/items?itemName=Prisma.prisma-insider)\r\n[![Installs](https://vsmarketplacebadge.apphb.com/installs/prisma.Prisma.svg)](https://marketplace.visualstudio.com/items?itemName=Prisma.prisma-insider)\r\n[![Ratings](https://vsmarketplacebadge.apphb.com/rating/prisma.Prisma.svg)](https://marketplace.visualstudio.com/items?itemName=Prisma.prisma-insider)\r\n\r\n![CI tests](https://img.shields.io/github/workflow/status/prisma/vscode/CI%20tests/master.svg?label=CI%20tests&logo=github)\r\n![Check for Update + Automated Publish](https://img.shields.io/github/workflow/status/prisma/vscode/Check%20for%20Update%20%2B%20Automated%20Publish/master.svg?label=Check%20for%20Update%20%2B%20Automated%20Publish&logo=github)\r\n\r\n\r\n</div>\r\n<hr>\r\n\r\n## Insider Build\r\n\r\nThis is the Insider Build of the [Prisma VSCode extension](https://marketplace.visualstudio.com/items?itemName=Prisma.prisma). Most users should not use this version, but instead install\r\nthe regular version of the extension.This version of the extension may contain unstable prerelease code and is directly built from the master branch. \r\n\r\n**Only use this extension if you are also using the dev version of the CLI.**\r\n\r\nPlease note that you should not have the regular and insider version of the extension installed at the same time.\r\n\r\n## Build information\r\n\r\nThis version is built from commit [sha](sha).\r\nThis is for Prisma CLI [2.5.1-dev.1](2.5.1-dev.1).\r\n\r\n## Contributing\r\n\r\nRead more about [how to contribute to the Prisma VSCode extension](./packages/vscode/CONTRIBUTING.md)\r\n\r\n## Telemetry\r\n\r\nThis extension collects telemetry data using [Azure Application Insights](https://www.npmjs.com/package/vscode-extension-telemetry) to help us better the usage of the extension.\r\nThe extension respects the `telemetry.enableTelemetry` setting in VSCode.\r\n\r\n## Security\r\n\r\nIf you have a security issue to report, please contact us at [security@prisma.io](mailto:security@prisma.io?subject=[GitHub]%20Prisma%202%20Security%20Report%20VSCode)\r\n')
  })

  it('it should work with a stable release', () => {
    expect(
        getNewReadMeContent({
            releaseChannel: 'latest',
            npmVersion: '2.4.0',
            githubActionContextSha: 'sha'
          })
    ).to.eq('<h2 align="center">Prisma VS Code Extension</h2>\r\n<div align="center">\r\n\r\n[![Version](https://vsmarketplacebadge.apphb.com/version/prisma.Prisma.svg)](https://marketplace.visualstudio.com/items?itemName=Prisma.prisma)\r\n[![Installs](https://vsmarketplacebadge.apphb.com/installs/prisma.Prisma.svg)](https://marketplace.visualstudio.com/items?itemName=Prisma.prisma)\r\n[![Ratings](https://vsmarketplacebadge.apphb.com/rating/prisma.Prisma.svg)](https://marketplace.visualstudio.com/items?itemName=Prisma.prisma)\r\n\r\n</div>\r\n<hr>\r\nAdds syntax highlighting, formatting, jump-to-definition and linting for Prisma Schema files.\r\n\r\n## Features\r\n\r\n* Syntax highlighting\r\n* Code Completion\r\n    * Completion results appear for symbols as you type. \r\n    * You can trigger this manually with the Ctrl+Space shortcut.\r\n* Documentation help\r\n    * Information about the documentation of a completion result pops up as completion results are provided.\r\n* Quick info on hover\r\n    * Documentation Comments (`///`) of models and enums appear anywhere you hover over their usages.\r\n* Go to Definition\r\n    * Jump to or peek a model or enum\'s declaration.\r\n* Formatting\r\n    * Format code either manually or on save (if configured). \r\n    * *To automatically format on save, add the following to your `settings.json` file:*\r\n        ```\r\n        "editor.formatOnSave": true\r\n        ```\r\n* Rename\r\n    * Rename models, enums, fields and enum values\r\n    * Automatically applies `@map` or `@@map` on the schema \r\n* Linting\r\n    * Diagnostic tools are used to surface errors and warnings in your schema file as you type.\r\n* Quick-fixes\r\n    * Quickly fix typos in model and enum names\r\n    * Create new models and enums with a single click\r\n\r\n\r\n## Preview\r\n\r\n<details>\r\n  <summary>Syntax-Highlighting</summary>\r\n\r\n![Preview Schema](https://i.imgur.com/W80iRwE.png)\r\n\r\n</details>\r\n<details>\r\n  <summary>Quick-Fixes</summary>\r\n  \r\n![Quick-Fixes](https://media.giphy.com/media/iGGCF9JWOHx7SAKQlu/giphy.gif)\r\n</details>\r\n\r\n## Contributing\r\n\r\nRead more about [how to contribute to the Prisma VSCode extension](./packages/vscode/CONTRIBUTING.md)\r\n\r\n## Telemetry\r\n\r\nThis extension collects telemetry data using [Azure Application Insights](https://www.npmjs.com/package/vscode-extension-telemetry) to help us better the usage of the extension.\r\nThe extension respects the `telemetry.enableTelemetry` setting in VSCode.\r\n\r\n## Build information\r\n\r\nThis is for Prisma CLI [2.4.0](2.4.0).\r\n\r\n## Security\r\n\r\nIf you have a security issue to report, please contact us at [security@prisma.io](mailto:security@prisma.io?subject=[GitHub]%20Prisma%202%20Security%20Report%20VSCode)\r\n')
  })
})
