name: Bump versions for extension only

on:
    push:
      branches: # TODO patch-branch!
        - 'master'


jobs:
  bump:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Setup Git
        run: |
          git config --global user.email "prismabots@gmail.com"
          git config --global user.name "Prismo"
          git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git" || true
      - name: Update version in scripts folder and push to master
        id: update
        run: npm run bump-extension-version-in-scripts dev
      - name: Push to master
        run: |
          git add -A .
          git commit -m "bump extension version to ${{ steps.update.next-vscode-version }}."
          git push
      - name: Update VSCode extension version
        run:  npm run   ${{ steps.update.outputs.next-vscode-version }}
      - name: Push to branch
        run: 
      - name: Trigger next workflow for LSP Unit tests
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Unit tests for LSP and bump LSP version
          token: ${{ secrets.GH_TOKEN }}
          inputs: '{ "npm-channel": "dev" }'
