name: Bump versions

on:
  workflow_dispatch:
    inputs:
      npm-channel:
        description: 'Prisma CLI NPM Channel'
        required: true
      version:
        description: 'New Prisma CLI version'
        required: true

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  bump:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install Semver # Needed to use semver in scripts
        run: npm install
      - name: Setup Git
        run: |
          git config --global user.email "prismabots@gmail.com"
          git config --global user.name "Prismo"
          git remote add github "https://$GITHUB_ACTOR:$GH_TOKEN@github.com/$GITHUB_REPOSITORY.git" || true
      - name: Update versions in scripts folder 
        run: npm run bump-prisma-version-in-scripts ${{ github.event.inputs.npm-channel }} ${{ github.event.inputs.version }}
      - name: Update next extension version in scripts folder
        id: update
        run: npm run bump-extension-version-in-scripts ${{ github.event.inputs.npm-channel }}
      - name: Push to master
        run: |
          git add -A .
          git commit -m "bump Prisma CLI ${{ github.event.inputs.npm-channel }} version to ${{ github.event.inputs.version }} and extension version to ${{ steps.update.next-extension-version }} in scripts."
          git push
      - name: Switch branch 
        if: ${{ github.event.inputs.npm-channel }} != "dev"
        run: npm run setup:branch ${{ github.event.inputs.npm-channel }}
      - name: Update Prisma CLI version and VSCode extension version
        run:  npm run bump-versions-in-repo ${{ github.event.inputs.npm-channel }} ${{ steps.update.outputs.next-extension-version }} ${{ github.event.inputs.version }} 
      - name: Push to branch
        run: |
          git add -A .
          git commit -m "bump extension version to ${{ steps.update.next-extension-version }} in package.json"
          git push
      - name: Trigger next workflow for LSP Unit tests
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Unit tests for LSP and bump LSP version
          token: ${{ secrets.GH_TOKEN }}
          inputs: '{ "npm-channel": "${{ github.event.inputs.npm-channel }}" , "extension-version": "${{ steps.update.next-extension-version }}"}'
