name: Unit tests for LSP and bump LSP version

on:
  workflow_dispatch:
    inputs:
      npm-channel:
        description: 'Prisma CLI NPM Channel'
        required: true

jobs:
  tests:
    name: Run unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps: 
      - uses: actions/checkout@v2
      - name: Install Dependencies in LSP
        run: cd packages/language-server && npm install
      - name: Compile LSP
        run: cd packages/language-server && npm run build
      - name: LSP unit tests
        run: cd packages/language-server && npm test

  bump:
    name: Bump LSP version
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get new version
        run: 
      - name: Commit version to scripts version file
        run: 
      - name: Commit and push to branch 
        run: 
      - name: Publish to npm
        run: 
      - name: Trigger next workflow for bumping LSP in extension
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Bump LSP in VSCode extension
          token: ${{ secrets.GH_TOKEN }}
          inputs: '{ "npm-channel": "dev" }'
